docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
    - Reference:
      - "Static Resources": static-resources.md
      - Logging: logging.md
      - "How it works": how_it_works.md
site_name: 'mezzio-swoole'
site_description: 'Swoole support for Mezzio'
repo_url: 'https://github.com/mezzio/mezzio-swoole'
